version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_jwbook
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1111'
      MYSQL_DATABASE: 'jwbook'
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: