spring:
  application:
    name: study308

  datasource:
    url: jdbc:mysql://localhost:3306/jwbook?serverTimezone=UTC
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update